// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/kecamatan/:id": {
    params: {
      "id": string;
    };
  };
  "/desa/:id": {
    params: {
      "id": string;
    };
  };
  "/open-data": {
    params: {};
  };
  "/open-data/:slug": {
    params: {
      "slug": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/kecamatan/:id" | "/desa/:id" | "/open-data" | "/open-data/:slug" | "/sitemap.xml" | "/robots.txt" | "/*";
  };
  "routes/map-layout.tsx": {
    id: "routes/map-layout";
    page: "/" | "/kecamatan/:id" | "/desa/:id";
  };
  "routes/map-home.tsx": {
    id: "routes/map-home";
    page: "/";
  };
  "routes/map-kecamatan.tsx": {
    id: "routes/map-kecamatan";
    page: "/kecamatan/:id";
  };
  "routes/map-desa.tsx": {
    id: "routes/map-desa";
    page: "/desa/:id";
  };
  "routes/open-data-layout.tsx": {
    id: "routes/open-data-layout";
    page: "/open-data" | "/open-data/:slug";
  };
  "routes/open-data-index.tsx": {
    id: "routes/open-data-index";
    page: "/open-data";
  };
  "routes/open-data-detail.tsx": {
    id: "routes/open-data-detail";
    page: "/open-data/:slug";
  };
  "routes/sitemap.ts": {
    id: "routes/sitemap";
    page: "/sitemap.xml";
  };
  "routes/robots.ts": {
    id: "routes/robots";
    page: "/robots.txt";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/map-layout": typeof import("./src/routes/map-layout.tsx");
  "routes/map-home": typeof import("./src/routes/map-home.tsx");
  "routes/map-kecamatan": typeof import("./src/routes/map-kecamatan.tsx");
  "routes/map-desa": typeof import("./src/routes/map-desa.tsx");
  "routes/open-data-layout": typeof import("./src/routes/open-data-layout.tsx");
  "routes/open-data-index": typeof import("./src/routes/open-data-index.tsx");
  "routes/open-data-detail": typeof import("./src/routes/open-data-detail.tsx");
  "routes/sitemap": typeof import("./src/routes/sitemap.ts");
  "routes/robots": typeof import("./src/routes/robots.ts");
  "routes/not-found": typeof import("./src/routes/not-found.tsx");
};