// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/kecamatan/:kecamatanSlug": {
    params: {
      "kecamatanSlug": string;
    };
  };
  "/desa/:desaSlug": {
    params: {
      "desaSlug": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/kecamatan/:kecamatanSlug" | "/desa/:desaSlug" | "/sitemap.xml" | "/robots.txt";
  };
  "routes/layout-peta.tsx": {
    id: "routes/layout-peta";
    page: "/" | "/kecamatan/:kecamatanSlug" | "/desa/:desaSlug";
  };
  "routes/beranda.tsx": {
    id: "routes/beranda";
    page: "/";
  };
  "routes/kecamatan-detail.tsx": {
    id: "routes/kecamatan-detail";
    page: "/kecamatan/:kecamatanSlug";
  };
  "routes/desa-detail.tsx": {
    id: "routes/desa-detail";
    page: "/desa/:desaSlug";
  };
  "routes/sitemap-xml.ts": {
    id: "routes/sitemap-xml";
    page: "/sitemap.xml";
  };
  "routes/robots-txt.ts": {
    id: "routes/robots-txt";
    page: "/robots.txt";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout-peta": typeof import("./app/routes/layout-peta.tsx");
  "routes/beranda": typeof import("./app/routes/beranda.tsx");
  "routes/kecamatan-detail": typeof import("./app/routes/kecamatan-detail.tsx");
  "routes/desa-detail": typeof import("./app/routes/desa-detail.tsx");
  "routes/sitemap-xml": typeof import("./app/routes/sitemap-xml.ts");
  "routes/robots-txt": typeof import("./app/routes/robots-txt.ts");
};